apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  workflow:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          sleep 5
      - name: Say hi
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          sleep 5
      - name: Fail step
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          sleep 5
          exit 1
      - name: Test
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world testing"
          sleep 5
      - name: Deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world deploying"
          sleep 5
      - name: Automated Test
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world auto testing"
          sleep 5
      - name: Release
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world release"
          sleep 5
